### ISSUE TITLE
Add Plausible analytics

### ISSUE THREAD

**Issue by JackGilmore** [OpenDataScotland/opendata.scot_docs#3]
**Is your feature request related to a problem? Please describe.**
It would be useful to track what documentation pages are being used the most

**Describe the solution you'd like**
Add the same Plausible analytics script to the site 

**Describe alternatives you've considered**
N/A

**Additional context**
ODS project admin (Jack/Karen) will need to do as only they have access to the Plausible account

**Comment by KarenJewell** [comment]
Ooo good one!

**Comment by JackGilmore** [comment]
Deployed in https://github.com/OpenDataScotland/opendata.scot_docs/commit/ffb8bc439525dcda2545fca50b2cde3e1b943c02

Analytics can be viewed at https://plausible.io/docs.opendata.scot
